import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { List, Task } from '../types';

export const exportListToPdf = (list: List, tasks: Task[]) => {
  const doc = new jsPDF();

  // App Title Header
  doc.setFontSize(22);
  doc.setTextColor(108, 99, 255); // #6C63FF
  doc.text('Task Buddy', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Export Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 27);

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(14, 30, 196, 30);

  // List Meta Info
  doc.setFontSize(16);
  doc.setTextColor(30, 33, 48);
  doc.text(`List: ${list.title}`, 14, 40);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  if (list.description) {
    doc.text(`Description: ${list.description}`, 14, 46);
  }

  const deadlineText = list.deadline
    ? `Deadline: ${new Date(list.deadline).toLocaleDateString()}`
    : 'Deadline: None';
  doc.text(deadlineText, 14, list.description ? 52 : 46);

  // Prepare table data
  const tableRows = tasks.map((task) => {
    const status = task.is_completed ? 'Completed' : 'Pending';
    const dueDate = task.due_date ? new Date(task.due_date).toLocaleDateString() : 'N/A';
    const priority = task.priority.toUpperCase();

    return [
      '[  ]', // Printable Checkbox
      task.title,
      task.description || '-',
      priority,
      dueDate,
      status,
    ];
  });

  const startY = list.description ? 58 : 52;

  autoTable(doc, {
    startY: startY,
    head: [['[ ]', 'Task Title', 'Description', 'Priority', 'Due Date', 'Status']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [108, 99, 255],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
    },
    columnStyles: {
      0: { cellWidth: 15, halign: 'center' }, // Checkbox
      1: { cellWidth: 45 },                  // Title
      2: { cellWidth: 50 },                  // Description
      3: { cellWidth: 25 },                  // Priority
      4: { cellWidth: 25 },                  // Due date
      5: { cellWidth: 22 },                  // Status
    },
    didParseCell: (data) => {
      // Color-code priority column
      if (data.section === 'body' && data.column.index === 3) {
        const priorityVal = data.cell.raw as string;
        if (priorityVal === 'HIGH') {
          data.cell.styles.textColor = [220, 38, 38]; // Red
          data.cell.styles.fontStyle = 'bold';
        } else if (priorityVal === 'MEDIUM') {
          data.cell.styles.textColor = [217, 119, 6]; // Amber
        } else if (priorityVal === 'LOW') {
          data.cell.styles.textColor = [16, 185, 129]; // Green
        }
      }

      // Format completed task titles
      if (data.section === 'body' && data.column.index === 1) {
        const rowIndex = data.row.index;
        if (tasks[rowIndex]?.is_completed) {
          data.cell.styles.textColor = [140, 140, 140];
        }
      }
    },
    didDrawCell: (data) => {
      // Draw a clean physical box for printable checkbox cell in column 0
      if (data.section === 'body' && data.column.index === 0) {
        const { x, y, width, height } = data.cell;
        const boxSize = 5;
        const boxX = x + (width - boxSize) / 2;
        const boxY = y + (height - boxSize) / 2;

        doc.setDrawColor(100, 100, 100);
        doc.setLineWidth(0.4);
        doc.rect(boxX, boxY, boxSize, boxSize);

        const rowIndex = data.row.index;
        if (tasks[rowIndex]?.is_completed) {
          // Draw checkmark inside
          doc.setDrawColor(108, 99, 255);
          doc.line(boxX + 1, boxY + 2.5, boxX + 2.2, boxY + 4);
          doc.line(boxX + 2.2, boxY + 4, boxX + 4, boxY + 1);
        }
      }
    },
  });

  // Footer with Page Numbers
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Task Buddy', 14, 287);
    doc.text(`Page ${i} of ${totalPages}`, 180, 287);
  }

  // Save File
  const filename = `${list.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_tasks.pdf`;
  doc.save(filename);
};
